version: '2'
services:
    web:
       build: ./web-proxy
       command: ./myproxy 12345
       volumes:
         - ./web-proxy:/code
         - ./logs:/var/log/erss
       ports:
         - "12345:12345"
       